spring.application.name=medinear
spring.datasource.url = jdbc:postgresql://127.0.0.1:5432/medinear
spring.datasource.username = postgres
spring.datasource.password = 12345
spring.jpa.hibernate.ddl-auto=update
server.port=8081


jwt.secret=medinearprojectjwtsecretkeymedinearprojectjwtsecretkey123456
jwt.expiration=86400000

